services:
  order-db:
    image: mongo
    container_name: order-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: orders
    ports:
      - 27017:27017
    networks:
      - order-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8084:8081 # Access via localhost:8084
    environment:
      # Option A: The Full URL (Notice the admin authSource)
      ME_CONFIG_MONGODB_URL: mongodb://root:example@order-db:27017/
      
      # Option B: Explicit Config (Highly Recommended)
      ME_CONFIG_MONGODB_SERVER: order-db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      # Web UI Auth
      ME_CONFIG_BASICAUTH_ENABLED: "false"
    networks:
      - order-network
    depends_on:
      - order-db

networks:
  order-network:
    driver: bridge

volumes:
  order-db-data: