services:
  product-db:
    image: postgres:15-alpine
    container_name: postgres-product-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product-db
    ports:
      - "5432:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data

volumes:
  product-db-data: